---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - put: docker-image
    params:
      build: git-repo/ci

resources:
- name: git-repo
  type: git
  source:
    uri: ((github-uri))
    branch: master
    private_key: ((publishing-outputs-private-key))

- name: docker-image
  type: docker-image
  source:
    email: ((dockerhub-email))
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    repository: ((dockerhub-repository))